---
- name: "Fail on unrecognized system"
  ansible.builtin.fail:
    msg: "Couldn't recognize remote host OS"
  when: ansible_system != 'Win32NT' and ansible_system != 'Linux'

- name: "VEN Pair"
  block:

    - include_tasks: pairing_profile.yml

    - include_tasks: pair_linux.yml
      when: ansible_system == 'Linux'

    - include_tasks: pair_windows.yml
      when: ansible_system == 'Win32NT'

  tags:
    - ven_pair

- include_tasks: manage_ven_linux.yml
  when: ansible_system == 'Linux'
  tags:
    - always

- include_tasks: manage_ven_windows.yml
  when: ansible_system == 'Win32NT'
  tags:
    - always
