---
# VEN role defaults
- name: "VEN | Pair"
  block:

    - include_tasks: pairing_profile.yml

    - include_tasks: pair_linux.yml
      when: ansible_system == 'Linux'

    - include_tasks: pair_windows.yml
      when: ansible_system == 'Windows'

  always:

    - name: "Remove temporary pairing profile"
      uri:
        url: "https://{{ illumio_pce_hostname }}:{{ illumio_pce_port }}/api/v2/orgs/{{ illumio_pce_org_id }}/pairing_profiles/{{ illumio_pairing_profile_id }}"
        user: "{{ illumio_pce_api_key }}"
        password: "{{ illumio_pce_api_secret }}"
        force_basic_auth: yes
        method: DELETE
        status_code: 204
      no_log: yes
      ignore_errors: yes
      when: temporary_profile is defined and temporary_profile
      tags:
        - always

  when: not illumio_ven_unpair

- name: "VEN | Unpair"
  block:

    - include_tasks: unpair.yml

  when: illumio_ven_unpair
