---
- name: "Fail on unrecognized system"
  ansible.builtin.fail:
    msg: "Couldn't recognize remote host OS"
  when: ansible_system != 'Windows' and ansible_system != 'Linux'

- name: "VEN | Pair"
  block:

    - include_tasks: pairing_profile.yml

    - include_tasks: pair_linux.yml
      when: ansible_system == 'Linux'

    - include_tasks: pair_windows.yml
      when: ansible_system == 'Windows'

  tags:
    - ven_pair

- include_tasks: manage_ven.yml
  tags:
    - always
