---
- name: "Get VEN HREF"
  uri:
    url: "https://{{ illumio_pce_hostname }}:{{ illumio_pce_port }}/api/v2/orgs/{{ illumio_pce_org_id }}/workloads?managed=true&hostname={{ ansible_hostname }}&max_result=1"
    user: "{{ illumio_pce_api_key }}"
    password: "{{ illumio_pce_api_secret }}"
    force_basic_auth: yes
    method: GET
    status_code: 200
    return_content: yes
  register: workload_response
  no_log: yes

- debug:
    msg: "No managed workload found to unpair with hostname {{ ansible_hostname }}"
  when: workload_response.json | length == 0

- name: "Run unpair"
  block:

    - name: "Set VEN HREF"
      set_fact:
        ven_href: "{{ workload_response.json[0]['ven']['href'] }}"

    - name: "Unpair VEN"
      uri:
        url: "https://{{ illumio_pce_hostname }}:{{ illumio_pce_port }}/api/v2/orgs/{{ illumio_pce_org_id }}/vens/unpair"
        user: "{{ illumio_pce_api_key }}"
        password: "{{ illumio_pce_api_secret }}"
        force_basic_auth: yes
        method: PUT
        status_code: [200, 204]
        body_format: json
        body:
          vens:
            - href: "{{ ven_href }}"
          firewall_restore: "default"
        headers:
          Content-Type: application/json
      no_log: yes

  when: workload_response.json | length > 0
